/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.3.1/samples
 */
plugins {
	id("application")
	id("java")
}


application {
	mainClass = "Main"
}

repositories {
	mavenCentral()
	mavenLocal()
}

dependencies {
    testImplementation(platform("org.junit:junit-bom:5.9.1"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    implementation("com.opencsv:opencsv:5.12.0")
}


tasks.test {
    useJUnitPlatform()
} 
tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}

testing {
    suites {
        "test"(JvmTestSuite::class) {
            useJUnitJupiter()
            dependencies {
                implementation(platform("org.springframework.boot:spring-boot-dependencies:3.4.6"))
                implementation("org.springframework.boot:spring-boot-starter-test")
            }
        }
    }
}

